### ISSUE TITLE
Error when run eb deploy for the second time

### ISSUE THREAD

**Issue by yemilgr** [rennokki/laravel-aws-eb#11]
First time laravel app deploys ok, but next time i ran eb deploy EB throws and error. When i check logs seems to be trying to exec the same scripts in .platform 

How to avoid this ??

Thanks

**Comment by rennokki** [comment]
Hey @yemilgr.

The `.platform/` folder contains only scripts that will be running on each deployment, there is no way to avoid that because that's how the deployment process is built.
