### ISSUE TITLE
Should I configure  Laravel Queue worker manually?

### ISSUE THREAD

**Issue by basnetjiten** [rennokki/laravel-aws-eb#14]
Hi there, I just saw inside .platform/files/supervise.ini there is the command for artisan horizon.  I believe this is the command executed in beanstalk. In my laravel project I haven't use horizon. My current requirement is to just run artisan queue:work. Do I have to change this command to make my way or it comes out of box with horizon. Also Iam using Aws SQS as my queue driver and not Redis. So Can I still use your configuration ? 
[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/app/current/artisan horizon
autostart=true
autorestart=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/dev/null

**Comment by rennokki** [comment]
Hi!

The snippet you sent me is a configuration for Supervisor, so you can set as many commands as you'd like that you want to be daemonized.

So yes, you can set a `queue:work` for SQS if you'd like to:

```ini
[program:laravel-sqs-queue]
process_name=%(program_name)s_%(process_num)02d
command=php /var/app/current/artisan queue:work sqs [the rest of the command]
autostart=true
autorestart=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/dev/null
```
