### ISSUE TITLE
Supervisor running but not processing jobs

### ISSUE THREAD

**Issue by eperedo** [rennokki/laravel-aws-eb#15]
Hi, I was able to get supervisor up and running, but for an unkown reason supervisor is not processing the jobs in my default queue. 

![super_logs](https://user-images.githubusercontent.com/461124/87462505-a975d880-c5d5-11ea-8913-51e95d021e1c.png)

This is my supervisor conf:

```
[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/app/current/artisan queue:work --queue=default --tries=1
autostart=true
autorestart=true
user=root
numprocs=4
redirect_stderr=true
stdout_logfile=/dev/null
```

Is there any log I can read to know what is the possible error? Thanks in advanced for any kind of help.

**Comment by rennokki** [comment]
Hey, it seems like it's more of a problem regarding the command itself. Try to cd into the directory and run the command.

If that doesn't work, you can enable the debugging by changing `stdout_logfile` from `/dev/null` to some path, usually it is `/var/log/supervisor/worker.log` for example.

I can see it might be a problem here with not specifying a directory and I might address a PR for this: 
set a `directory=/var/app/current` and change the `command` line with `command=php artisan queue:work [rest of args here]`

**Comment by eperedo** [comment]
Thanks for the answer, turns out supervisor is  actually running the jobs but without any environment variables (which I added via App -> Env -> Config -> Software Config. option -> Env Properties) so by default is trying to connect to **127.0.0.1:6379** instead my **REDIS_HOST** variable. 

I know this is outside the scope of this repo, but any idea why supervisor is not catching env variables?

Nice work with this project, It  really made my day easier 👍

**Comment by rennokki** [comment]
By the env variables you're talking it's about the ones you set in the AWS Console or in your .env file?

**Comment by eperedo** [comment]
The aws console.

I just realized that AWS is generating a env file in: **/opt/elasticbeanstalk/deployment/env**. So I have copied this file to the app directory and it's working fine now. Not sure if it is the best solution though.

My ```hooks/postdeploy/restart_file.sh```
```bash
#!/bin/bash
sudo cp /opt/elasticbeanstalk/deployment/env /var/app/current/.env

sudo supervisorctl restart all
```

**Comment by rennokki** [comment]
As long as you are using the env generated by AWS it should be fine. The only thing is that you should run the copy command in a file from .ebextensions, in a container_command just like the 01_deploy.config example shipped by default. Adding it in a postdeploy hook will copy the env file after the deployment switched the live to the new version.
