### ISSUE TITLE
Unable to chmod +x .platform/hooks/postdeploy/make_folders_writable.sh permission issue on windows

### ISSUE THREAD

**Issue by Ali-Shaikh** [rennokki/laravel-aws-eb#17]
I am running chmod +x .platform/hooks/postdeploy/make_folders_writable.sh using gitbash on windows and then deploying but I am getting 
2020/07/14 19:37:57.634916 [ERROR] An error occurred during execution of command [app-deploy] - [RunPostDeployHooks]. Stop running the command. Error: Command .platform/hooks/postdeploy/make_folders_writable.sh failed with error fork/exec .platform/hooks/postdeploy/make_folders_writable.sh: permission denied

**Comment by rennokki** [comment]
See the related issues & their solving: https://github.com/rennokki/laravel-aws-eb/issues/8, https://github.com/rennokki/laravel-aws-eb/issues/10
