### ISSUE TITLE
Seed DB

### ISSUE THREAD

**Issue by 2JN** [rennokki/laravel-aws-eb#25]
On .ebextensions/01_deploy.config

for the command: "php artisan migrate --force"
if you change it to "php atisan migrate:fresh --seed --forece"

it fails. Is there any way to seed the DB on EB ?

**Comment by SergejSi** [comment]
07_run_seed:
     command: "php artisan db:seed --force"
    leader_only: true
    cwd: "/var/app/staging"

**Comment by dhrumil4u360** [comment]
@2JN I wonder what type of scenario you are dealing with so that you need to do `migrate:fresh` for every deployment!! I mean it will simply reset your DB every time.
