### ISSUE TITLE
Apache configuration 

### ISSUE THREAD

**Issue by nitishxp** [rennokki/laravel-aws-eb#26]
Can you please also provide a apache2 config ?

**Comment by rennokki** [comment]
The AL2 version came at first with NGINX, so the configuration couldn't be done at the project-level using `.htaccess` like Apache does. So for that case, you should use the `public/.htaccess` file to make changes to the reverse proxy of your own.

**Comment by nitishxp** [comment]
So you meant, use the nginx and overwrite the nginx.conf to handle all the things right?

**Comment by rennokki** [comment]
Add a `public/.htaccess` in your Laravel project and config it from there. everything should work fine.
