### ISSUE TITLE
How can ignore the file .env from s3 and run the real one in the project?

### ISSUE THREAD

**Issue by jeanali** [rennokki/laravel-aws-eb#35]
I don't use env_file.config file to upload the  .env  propertiy, so I just delete it! then upload my project with `APP_ENV=production` and etc ... but some properties like `APP_ENV=production` and `APP_DEBUG=false` does not work ? 

How can use my own `.env` ?

**Comment by jeanali** [comment]
Another question:

I need just three things:

- CRON job for multi instance( when the app make auto scaling) 
- Supervisor for multi instance( when the app make auto scaling) 

What file should I keep and delete others unnecessary file ?

**Comment by kylemilloy** [comment]
You can set environment variables through the elastic beanstalk UI.
