### ISSUE TITLE
Access Denied s3 .env

### ISSUE THREAD

**Issue by tcagkansokmen** [rennokki/laravel-aws-eb#36]
Hi there,

Tried to copy .env file from s3, but It couldn't reach the file. (file doesnt have public access)

Is there anyway to copy it with AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY ?

**Comment by rennokki** [comment]
You can take a look at the `00_copy_env_file.config`: https://github.com/rennokki/laravel-aws-eb/blob/master/.ebextensions/00_copy_env_file.config

You got instructions on how to specify the process of copying from the S3 bucket (it has to be the Elastic Beanstalk bucket)
