### ISSUE TITLE
Discarding statistic item after validation error

### ISSUE THREAD

**Issue by tcagkansokmen** [rennokki/laravel-aws-eb#37]
Hi there,

My ebs server is returning "severe" status and my error log is like:

"W, [2020-10-24T05:48:33.136544 #31841]  WARN -- : discarding statistic item after validation error (Invalid timestamp): {:id=>"7", :namespace=>"application", :timestamp=>1603516780, :data=>"{\"duration\":10,\"latency_histogram\":[[0.024,1]],\"http_counters\":{\"status_302\":1,\"request_count\":1}}"}"

What could be the reason?

**Comment by rennokki** [comment]
I assume the issue has been resolved so far.

**Comment by charliemr99** [comment]
I have the same issue, does anybody know anything about this error?

**Comment by thonymg** [comment]
same to me

**Comment by rennokki** [comment]
It seems like an issue regarding Enhanced Health Monitoring. Try disabling it.

**Comment by DarkIsDude** [comment]
Thanks a lot @rennokki. We tried to switch from t3.medium to c6a.xlarge. Impossible with `Enhanced Health Monitoring` enabled. We disabled it, did the upgrade, enabled it again and all good now.
