### ISSUE TITLE
Incorrect storage link

### ISSUE THREAD

**Issue by abhyudayasrinet** [rennokki/laravel-aws-eb#43]
Running `php artisan storage:link` under `/var/app/staging` creates a link to the `staging` folder once the application is deployed

```
[ec2-user@ip-xxxx-xx-xx-xxx log]$ ls -ltr /var/app/current/public/
total 16
drwxrwxr-x 8 webapp webapp 4096 Jan 21 17:17 uploads
-rw-rw-r-- 1 webapp webapp   24 Jan 21 17:17 robots.txt
-rw-rw-r-- 1 webapp webapp 1731 Jan 21 17:17 index.php
drwxrwxr-x 2 webapp webapp   64 Jan 21 17:17 import
drwxrwxr-x 2 webapp webapp 4096 Jan 21 17:17 images
-rw-rw-r-- 1 webapp webapp    0 Jan 21 17:17 favicon.ico
lrwxrwxrwx 1 root   root     35 Jan 21 17:18 storage -> /var/app/staging/storage/app/public
```

Instead, running it as a `postdeploy` hook via a script generates the correct symlink

```
[ec2-user@ip-xxx-xx-xx-xxx log]$ ls -ltr /var/app/current/public/
total 16
drwxrwxr-x 8 webapp webapp 4096 Jan 21 17:26 uploads
-rw-rw-r-- 1 webapp webapp   24 Jan 21 17:26 robots.txt
-rw-rw-r-- 1 webapp webapp 1731 Jan 21 17:26 index.php
drwxrwxr-x 2 webapp webapp   64 Jan 21 17:26 import
drwxrwxr-x 2 webapp webapp 4096 Jan 21 17:26 images
-rw-rw-r-- 1 webapp webapp    0 Jan 21 17:26 favicon.ico
lrwxrwxrwx 1 root   root     35 Jan 21 17:27 storage -> /var/app/current/storage/app/public
```

**Comment by rennokki** [comment]
Does the symlink gets overwritten if it's run both in the deployment process and after the deployment finishes? I'm thinking about just adding a new .sh file to the `postdeploy` hook that does that, without removing the `01_deploy.config`'s `04_link_storage_folder`.

**Comment by abhyudayasrinet** [comment]
The first output was generated using the container_command after deployment succeeded. So we can see, it is still referring to the `staging` folder path, even though it doesn't exist after deployment.

Having it as a container_command in `01_deploy.config` would be of no use in this case and should be removed. I added the following script as a `postdeploy` hook and I get the correct symlink shown in the second output

```
#!/bin/bash

php artisan storage:link
```

**Comment by rennokki** [comment]
I assume that the public folder symlink is not needed in the deployment process by any means, right?

**Comment by rennokki** [comment]
I have tagged [v2.8.1](https://github.com/rennokki/laravel-aws-eb/releases/tag/v2.8.1)

**Comment by abhyudayasrinet** [comment]
Ideally, it shouldn't be since deployments would purge the storage folders but in the case if someone has a custom setup where they do use the storage folder, the symlink might be required.
