### ISSUE TITLE
Run queues / caching in eb evironment

### ISSUE THREAD

**Issue by SergejSi** [rennokki/laravel-aws-eb#45]
Hey rennokki thank you for the awesome package! 
 
I wanna run queues/ caching in my eb environment. 
What is the best way to do this?

Is this a good way to run queues as follows and use sqs as queue driver? 

> [program:laravel-sqs-queue]
process_name=%(program_name)s_%(process_num)02d
command=php /var/app/current/artisan queue:work sqs 
autostart=true
autorestart=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/dev/null

Or is there a way to install redis to the instance and use it for the above purpose?

**Comment by rennokki** [comment]
It depends on your purpose. You can use [all of the Laravel queue drivers with this configuration](https://laravel.com/docs/8.x/queues#driver-prerequisites).
