### ISSUE TITLE
Health Monitor

### ISSUE THREAD

**Issue by mchumer** [rennokki/laravel-aws-eb#49]
Hi!!

I have this issue:

![image](https://user-images.githubusercontent.com/12549150/117037756-36ad2980-acdd-11eb-9b6d-e9625cb8e973.png)

![image](https://user-images.githubusercontent.com/12549150/117037794-4462af00-acdd-11eb-9f8f-cf1461e6c57b.png)

All this data is blank. I'm researching to find a reason but i've found nothing till now.

Does somebody have any clues?

**Comment by mchumer** [comment]
I've found this article. 

https://www.dana.lol/2017/09/29/elastic-beanstalk-enhanced-health-reporting/

**Comment by mchumer** [comment]
I've figured out whats happening.. I've changed de server timezone, so Elb health was looking for files named like if it was 3 hours from now and, obviously, the file was not created yet. To solve this I quit trying to change the timezone on the server.

**Comment by rennokki** [comment]
@mchumer I highly recommend to keep using UTC for the server and transform the timezones within the app logic. I've been through this too.
