### ISSUE TITLE
composer not found in /opt/elasticbeanstalk/support

### ISSUE THREAD

**Issue by dhrumil4u360** [rennokki/laravel-aws-eb#5]
@rennokki First of thanks for this awesome repo. It saves lot of time!

I am using this configurations to deploy laravel on latest `aws-elasticbeanstalk-amzn-2.0.20200430.64bit-eb_php74_amazon_linux_2-hvm-2020-05-05T21-06 ` AMI.

It fails to deploy & `cfn-init-cmd.log` says :

```
[INFO] -----------------------Command Output-----------------------
[INFO] 	Could not open input file: /opt/elasticbeanstalk/support/composer.phar
[INFO] ------------------------------------------------------------
[ERROR] Exited with error code 1
```

When I replace `/opt/elasticbeanstalk/support` by `/user/bin`, it works fine! Am I beating any purpose of having `/opt/elasticbeanstalk/support` in )1_deploy file or you need to update that part in repo?

**Comment by rennokki** [comment]
Yeah, it's a mistake there.

You should be calling `php /usr/bin/composer.phar` instead of `composer`.

I'm going to fix that.

**Comment by rennokki** [comment]
Glad you like it. I am towards making other devops' life easier by simplifying things i wasted many hours on.

Fixed in: https://github.com/rennokki/laravel-aws-eb/commit/4ba79dfeed631e4fb2e3d7ed64636151ce260fb7
