### ISSUE TITLE
Composer install run by EB

### ISSUE THREAD

**Issue by giraz82** [rennokki/laravel-aws-eb#52]
According to EB documentation, it seems that `composer install` is run automatically if a `composer.json` file is detected: 
```
When a composer.json file is present, Elastic Beanstalk runs composer.phar install to install dependencies.
```
from https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/php-configuration-composer.html.

Indeed, if I look to `eb-engine.log` i see:
```
2021/06/07 17:27:38.644904 [INFO] Finished running the platform hooks in .platform/hooks/prebuild/
2021/06/07 17:27:38.644932 [INFO] Executing instruction: Install composer dependencies
2021/06/07 17:27:38.644947 [INFO] installing composer dependencies...
2021/06/07 17:27:38.645724 [INFO] Running command /bin/sh -c composer.phar install --no-ansi --no-interaction
```
That it's not the command `sudo php -d memory_limit=-1 /usr/bin/composer.phar install --no-dev --no-interaction --prefer-dist --optimize-autoloader` included in step `01_install_composer_dependencies` in `.ebextensions/01_deploy.config` file.

Unfortunately I'm getting
```
Mon Jun  7 17:27:41 2021 (6549): Fatal Error Insufficient shared memory!
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 254
```
And I'm not able to raise the memory for the composer process.

Any idea?
Thank you

**Comment by rennokki** [comment]
Hi @giraz82,

The composer installation step might come from AWS, but the command defined in the `01_deploy.config` is coming later in the process. You can find the logging in `cfn-init-cmd.log`.

The insufficient shared memory issue was already raised in the past. It's an EC2 limitation, even with unlimited memory workarounds. Please read this thread: https://github.com/rennokki/laravel-aws-eb/issues/41

**Comment by giraz82** [comment]
Hi @rennokki, sorry fo the delay.
Yes, I'm aware that that composer install step comes from AWS. In the documentation is stated that if there is a `composer.json` file and there is any `vendor` folder, `composer install` is triggered by AWS.
There is no way to specify more memory for that process.
I solved installing php dependencies locally in my ci flow, and then adding also the `vendor` folder to the build.

For now I don't see any other solution and I will stay with this one.

Thank you any way for sharing your great repo.
