### ISSUE TITLE
[pool www] pm.min_spare_servers(0) must be a positive value 

### ISSUE THREAD

**Issue by JagsGill123** [rennokki/laravel-aws-eb#53]
In AWS elastic beanstalk getting a php-fpm not running error caused only when the Elastic Beanstalk Load Balancer/Auto Scaler creates a new EC2 instance. Some instances get the Error and some don't

Getting error 
`[pool www] pm.min_spare_servers(0) must be a positive value `

Seems to be caused by 

`.platform/hooks/postdeploy/x_optimize_php.sh 
`

setting a negative value for pm.min_spare_servers sometimes. Doesn't happen all the time. but just enough to keep bring my site down when ever there is a spike in traffic and the load balance creates new instances. 

as a fix I think this should be put in the file to save someone else having the same issue. I have added to mine

`
if (( ($MAX_CHILDREN > 0) && ($START_SERVERS > 0) && ($MIN_SPARE_SERVERS > 0) && ($MAX_SPARE_SERVERS > 0) && ($MIN_SPARE_SERVERS <= $MAX_CHILDREN) && ($MAX_SPARE_SERVERS <= $MAX_CHILDREN))); then
    sudo sed -i "s|pm.max_children.*|pm.max_children = $MAX_CHILDREN|g" /etc/php-fpm.d/www.conf
    sudo sed -i "s|pm.start_servers.*|pm.start_servers = $START_SERVERS|g" /etc/php-fpm.d/www.conf
    sudo sed -i "s|pm.min_spare_servers.*|pm.min_spare_servers = $MIN_SPARE_SERVERS|g" /etc/php-fpm.d/www.conf
    sudo sed -i "s|pm.max_spare_servers.*|pm.max_spare_servers = $MAX_SPARE_SERVERS|g" /etc/php-fpm.d/www.conf
fi
`

**Comment by rennokki** [comment]
On which instance type did this occur?

**Comment by JagsGill123** [comment]
> On which instance type did this occur?

Hi this happened on a t2.micro

after further investigation and manually running the calculations MAX_CHILDREN = around 2.99 or 3.1 
which for 
START_SERVERS=$(($MAX_CHILDREN / 4))
MIN_SPARE_SERVERS=$(($MAX_CHILDREN / 4))

will be 2.99/4 = 0.7475 which may be why it returns value as 0.

**Comment by rennokki** [comment]
I didn't take the smaller instances into account. At that point you will not need the PHP optimizer because there are too few resources.
